import React from "react";

import {
  SiReact,
  SiNodedotjs,
  SiExpress,
  SiMongodb,
  SiJavascript,
  SiGreensock,
  SiHtml5,
  SiCss3,
  SiTailwindcss,
  SiBootstrap,
  SiNextdotjs,
  SiEjs,
  SiPython,
  SiC,
  SiCplusplus,
  SiGit,
  SiGithub,
  SiKubernetes,
  SiCloudinary,
  SiVercel,
  SiRender,
  SiNetlify,
  SiResend,
  SiShadcnui,
  SiZod,
} from "react-icons/si";
import { VscAzure } from "react-icons/vsc";

export const skills = [
  { name: "React", icon: <SiReact className="text-blue-400" /> },
  { name: "Node.js", icon: <SiNodedotjs className="text-green-500" /> },
  { name: "Express", icon: <SiExpress className="text-gray-400" /> },
  { name: "MongoDB", icon: <SiMongodb className="text-green-600" /> },
  { name: "GSAP", icon: <SiGreensock className=" text-green-400" /> },
  { name: "JavaScript", icon: <SiJavascript className="text-yellow-400" /> },
  { name: "ES6+", icon: <SiJavascript className="text-purple-500" /> },
  { name: "HTML", icon: <SiHtml5 className="text-orange-500" /> },
  { name: "CSS", icon: <SiCss3 className="text-blue-500" /> },
  { name: "Tailwind", icon: <SiTailwindcss className="text-teal-400" /> },
  { name: "Bootstrap", icon: <SiBootstrap className="text-purple-600" /> },
  {
    name: "Next.js",
    icon: <SiNextdotjs className="text-white" />,
  },
  { name: "EJS", icon: <SiEjs className="text-red-500" /> },
  { name: "Python", icon: <SiPython color="#3776AB" /> },
  { name: "C", icon: <SiC color="#A8B9CC" /> },
  { name: "C++", icon: <SiCplusplus color="#00599C" /> },
  { name: "Git", icon: <SiGit className="text-[#F05032]" /> },
  { name: "GitHub", icon: <SiGithub className="text-[#181717]" /> },
  { name: "Azure", icon: <VscAzure className="text-[#0078D4]" /> },
  { name: "Cloudinary", icon: <SiCloudinary className="text-[#3448C5]" /> },
  { name: "Vercel", icon: <SiVercel className="text-white" /> },
  { name: "Render", icon: <SiRender className="text-[#46E3B7]" /> },
  { name: "Netlify", icon: <SiNetlify className="text-[#00C7B7]" /> },
  { name: "Resend", icon: <SiResend className="text-[#FFFFFF]" /> },

  { name: "Shadcn", icon: <SiShadcnui className="text-white" /> },
  { name: "Zod", icon: <SiZod  className="text-[#3E67B1]" /> },
];
